default: &default
  adapter: mysql2
  encoding: utf8
  username: hoge
  password: hoge

development:
  <<: *default
  database: denter_development

test:
  <<: *default
  database: denter_test

production:
  <<: *default
  username: sqale_b4c3d19cee
  password: a27670ee12bfbbb45d949d51bb089c232ff46ca38ba7e8ec
  database: sqale_b4c3d19cee
  host: mysql001.sqale.jp
