default: &default
  adapter: mysql2
  encoding: utf8
  username: hoge
  password: hoge

development:
  <<: *default
  database: reviewer_development

test:
  <<: *default
  database: reviewer_test

production:
  <<: *default
  database: reviewer_test
