default: &default
  adapter: mysql2
  encoding: utf8
  username: hoge
  password: hoge

development:
  <<: *default
  database: denter_development

test:
  <<: *default
  database: denter_test

production:
  <<: *default
  username: sqale_b229bd0546
  password: 3b479777e5df20e019dd1963735e3e8df530fa0e8352089f
  database: sqale_b229bd0546
  host: mysql001.sqale.jp
